### ISSUE TITLE
Question - config.yml

### ISSUE THREAD

**Issue by vthost** [vxfung/MatDeepLearn#12]
Thank you for providing all this code!
I am wondering how you selected the configurations in `config.yml`. Did you do hyperparameter tuning and, if so, on which data? Also, why did you choose CGCNN only in the ensemble, did it turn out to be best in general or is this to be considered as an example only?

**Comment by vxfung** [comment]
Hi,
The values in the config.yml are generic and just serve as example values. Similarly, only CGCNN is used in the ensemble as an example, but you may likely find a better performance with some other models in there as well. For hyperparameters obtained from a hyperparameter search on several different datasets, they can be found in the SI of the original publication here: https://www.nature.com/articles/s41524-021-00554-0. 
Best,
Victor
